# This GHA checks rOpenScPCA using dependencies using current packages from CRAN and Bioconductor

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

name: R-CMD-CHECK-release

jobs:
  R-CMD-check-release:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Check package
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual")'
